version: '3.3'
services:
    jenkins:
        build:
            context: ./jenkins/
            args:
                DOCKER_UID: 1000
                DOCKER_GID: 999
        container_name: jenkins
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_home:/var/jenkins_home
        ports:
            - "${JENKINS_WWW}:8080"
            - "${JENKINS_OTHER}:50000"
        expose:
            - "${JENKINS_WWW}"
            - "${JENKINS_OTHER}"
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
            - /:/host
        ports:
            - "9000:9000"
        expose:
            - "9000"
        environment:
            - CAP_HOST_MANAGEMENT=1
        
volumes:
    jenkins_home:
    portainer_data:
